// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCn-6ncx9YFOtwueVC1hMdC9062pqahoeY',
    appId: '1:784113112870:web:c503700a5046c05f8d13e7',
    messagingSenderId: '784113112870',
    projectId: 'wanderloom-5ace7',
    authDomain: 'wanderloom-5ace7.firebaseapp.com',
    storageBucket: 'wanderloom-5ace7.appspot.com',
    measurementId: 'G-WFM1F6XFRK',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAFg3jkz8BvlSnaNyhOHvu2uT5MKuJ13sQ',
    appId: '1:784113112870:android:9b1d751a2710efcf8d13e7',
    messagingSenderId: '784113112870',
    projectId: 'wanderloom-5ace7',
    storageBucket: 'wanderloom-5ace7.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBRSweeL-AWXebkzS2oN0jcRNjTMmzfNOQ',
    appId: '1:784113112870:ios:accdca88df68a8688d13e7',
    messagingSenderId: '784113112870',
    projectId: 'wanderloom-5ace7',
    storageBucket: 'wanderloom-5ace7.appspot.com',
    iosBundleId: 'com.example.wanderloom',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBRSweeL-AWXebkzS2oN0jcRNjTMmzfNOQ',
    appId: '1:784113112870:ios:621b49ba946c8c8f8d13e7',
    messagingSenderId: '784113112870',
    projectId: 'wanderloom-5ace7',
    storageBucket: 'wanderloom-5ace7.appspot.com',
    iosBundleId: 'com.example.wanderloom.RunnerTests',
  );
}
